name: "Build and Publish MkDocs Material"
description: "Build and Publish MkDocs Material to GitHub Pages using squidfunk's Docker image"
branding:
  icon: "layout"
  color: "green"

inputs:
  mkdocs-version:
    description: "MkDocs version"
    default: "latest"
    required: false
  config-file:
    description: "Path to the mkdocs.yml file"
    default: "mkdocs.yml"
    required: false
  requirements:
    description: "Path to the requirements.txt file"
    default: "mkdocs-requirements.txt"
    required: false

runs:
  using: "docker"
  image: "docker://squidfunk/mkdocs-material:latest"
  pre-entrypoint: |
    ls -al /;
    echo "PWD: ${PWD}";
    ls -al "${PWD}";
    echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}";
    ls -al ${GITHUB_WORKSPACE};
    echo "GITHUB_ACTION_PATH: ${GITHUB_ACTION_PATH}";
    ls -al "${GITHUB_ACTION_PATH}";
