name: "Build and Publish MkDocs Material"
description: "Build and Publish MkDocs Material to GitHub Pages using squidfunk's Docker image"

branding:
  icon: "layout"
  color: "green"

inputs:
  working-dir:
    description: "Folder where MkDocs will be called from"
    default: "."
    required: false
  site-dir:
    description: "Folder where MkDocs will save the generated site"
    default: "site"
    required: false
  config-file:
    description: "Path to the mkdocs.yml file"
    default: "mkdocs.yml"
    required: false
  requirements:
    description: "Path to the requirements.txt file"
    default: ""
    required: false

runs:
  using: "docker"
  image: "docker://squidfunk/mkdocs-material:latest"
  env:
    MKDOCS_WORKDIR: "${{ inputs.working-dir }}"
    MKDOCS_REQSTXT: "${{ inputs.requirements }}"
  entrypoint: "/github/workspace/entrypoint.sh"
  args:
    - "build"
    - "--verbose"
    - "--clean"
    - "--config-file"
    - "${{ inputs.config-file }}"
    - "--site-dir"
    - "${{ inputs.site-dir }}"
