name: "Test repo action"

on:
  # Triggered by hand
  workflow_dispatch:
  # Triggered by push
  push:
    paths:
      - 'action.yml'
      - '.github/workflows/test-action.yml'

jobs:
  my_first_job:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout this repository"
        uses: "actions/checkout@v1"

      - name: "Launch our action"
        uses: "./action.yml"
